spring:
  thymeleaf:
    cache: false
    cache-period: 0
    prefix: file:src/main/resources/templates/
  sql:
    init:
      mode: always
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql