spring:
  thymeleaf:
    cache: false
    cache-period: 0
    prefix: file:src/main/resources/templates/
  datasource:
    connectionProperties: useUnicode=true;characterEncoding=utf-8
    driver-class-name: org.postgresql.Driver
    password: msdbmk0729
    url: jdbc:postgresql://localhost:5432/msdbdatabase?currentSchema=msdb_miyadai
    username: km0729
  sql:
    init:
      mode: always
      data-locations: classpath:data/data.sql
management:
  endpoint:
    health:
      show-details: always
