version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: localdb
      POSTGRES_PASSWORD: root
